### PR TITLE
Updated for El Capitan

### PR DESCRIPTION
**Pull request by brandonusher**
Updated “Create New AppleID” instances, changed group numbers.

### CODE REVIEW

**Comment by brandonusher** [comment]
Once El Capitan is officially released I will update my test computer and try this out.

**Comment by stevejoyce** [comment]
Hi Brandonusher,

I just updated my work Mac to EI Capitan and updated iTunes to 12.3.0.44 and just tried your your really cool script today to discover Apple added a new field on the "Sign in to the iTunes Store" windows and this field is below Apple ID and Password. It a check box call "Remember password for purchases and free downloads" and of course it stops your script witch is to bad.  Apple they love to change things!!!

**Comment by brandonusher** [comment]
Hi stevejoyce,

Work became hectic after El Capitan so I haven't been able to test it yet.
I will try to set some time aside for testing this week and fix anything
new and "improved" in ITunes. Thanks for letting me know!

Sent from my iPhone

On Oct 6, 2015, at 16:28, stevejoyce <notifications@github.com> wrote:

Hi Brandonusher,

I just updated my work Mac to EI Capitan and updated iTunes to 12.3.0.44
and just tried your your really cool script today to discover Apple added a
new field on the "Sign in to the iTunes Store" windows and this field is
below Apple ID and Password. It a check box call "Remember password for
purchases and free downloads" and of course it stops your script witch is
to bad. Apple they love to change things!!!

—
Reply to this email directly or view it on GitHub
<https://github.com/brandonusher/Apple-ID-AppleScript/pull/29#issuecomment-146033030>
.

**Comment by stevejoyce** [comment]
Hi Brandousher,
No thank you for creating great resources like this for tech's who are just getting use to dealing with Apple, IPad's and apple ID's.... they do not make it easy for us that's for sure.

**Pull request merged**
